use super::{Result, StorageError, Store, ensure_regular_file, validate_digest};
use chrono::Utc;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{
    fs::{self, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
};
use uuid::Uuid;

pub const DERIVED_CACHE_FORMAT_VERSION: u32 = 1;
const MAX_DERIVED_CACHE_MANIFEST_BYTES: u64 = 64 * 1024;
const MAX_CACHE_KIND_BYTES: usize = 96;
const MAX_CACHE_SCOPE_BYTES: usize = 4096;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct DerivedCacheRecord {
    pub format_version: u32,
    pub scope_sha256: String,
    pub kind: String,
    pub fingerprint_sha256: String,
    pub blob_sha256: String,
    pub size_bytes: u64,
    pub work_units: u64,
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DerivedCacheHit {
    pub record: DerivedCacheRecord,
    pub blob_path: PathBuf,
    pub validated_bytes: u64,
}

fn invalid(message: impl Into<String>) -> StorageError {
    StorageError::InvalidDerivedCache(message.into())
}

fn digest_text(value: &str) -> String {
    hex::encode(Sha256::digest(value.as_bytes()))
}

fn validate_scope(scope: &str) -> Result<()> {
    if scope.is_empty() || scope.len() > MAX_CACHE_SCOPE_BYTES || scope.contains('\0') {
        return Err(invalid("cache scope is empty, too large, or contains NUL"));
    }
    Ok(())
}

fn validate_kind(kind: &str) -> Result<()> {
    if kind.is_empty()
        || kind.len() > MAX_CACHE_KIND_BYTES
        || !kind.bytes().all(|byte| {
            byte.is_ascii_lowercase() || byte.is_ascii_digit() || matches!(byte, b'-' | b'_' | b'.')
        })
    {
        return Err(invalid(
            "cache kind must be bounded lowercase ASCII using [a-z0-9._-]",
        ));
    }
    Ok(())
}

fn cache_key(scope_sha256: &str, kind: &str, fingerprint_sha256: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(scope_sha256.as_bytes());
    hasher.update([0]);
    hasher.update(kind.as_bytes());
    hasher.update([0]);
    hasher.update(fingerprint_sha256.as_bytes());
    hex::encode(hasher.finalize())
}

impl Store {
    fn derived_cache_root(&self) -> PathBuf {
        self.blob_root
            .parent()
            .unwrap_or_else(|| Path::new("."))
            .join("derived-cache")
    }

    fn derived_cache_manifest_path(
        &self,
        scope_sha256: &str,
        kind: &str,
        fingerprint_sha256: &str,
    ) -> Result<PathBuf> {
        validate_digest(scope_sha256)?;
        validate_digest(fingerprint_sha256)?;
        validate_kind(kind)?;
        let key = cache_key(scope_sha256, kind, fingerprint_sha256);
        Ok(self
            .derived_cache_root()
            .join("sha256")
            .join(&scope_sha256[..2])
            .join(scope_sha256)
            .join(format!("{key}.json")))
    }

    pub fn put_derived_cache_file(
        &self,
        scope: &str,
        kind: &str,
        fingerprint_sha256: &str,
        source: impl AsRef<Path>,
        work_units: u64,
    ) -> Result<DerivedCacheRecord> {
        validate_scope(scope)?;
        validate_kind(kind)?;
        validate_digest(fingerprint_sha256)?;
        let scope_sha256 = digest_text(scope);
        let destination =
            self.derived_cache_manifest_path(&scope_sha256, kind, fingerprint_sha256)?;
        let blob = self.ingest_blob_file(source)?;

        if destination.exists() {
            match self.lookup_derived_cache(scope, kind, fingerprint_sha256)? {
                Some(existing) => {
                    if existing.record.blob_sha256 != blob.sha256
                        || existing.record.size_bytes != blob.size_bytes
                    {
                        return Err(invalid(
                            "same scope/kind/fingerprint produced different verified bytes",
                        ));
                    }
                    return Ok(existing.record);
                }
                None => {
                    // A manifest whose blob was evicted may be repaired by regenerated bytes.
                    // The manifest remains sufficient to explain what needs rebuilding.
                }
            }
        }

        let record = DerivedCacheRecord {
            format_version: DERIVED_CACHE_FORMAT_VERSION,
            scope_sha256,
            kind: kind.to_owned(),
            fingerprint_sha256: fingerprint_sha256.to_owned(),
            blob_sha256: blob.sha256,
            size_bytes: blob.size_bytes,
            work_units,
            created_at: Utc::now().to_rfc3339(),
        };
        let encoded = serde_json::to_vec_pretty(&record)?;
        if encoded.len() as u64 > MAX_DERIVED_CACHE_MANIFEST_BYTES {
            return Err(invalid("cache manifest exceeds bounded manifest size"));
        }
        let parent = destination
            .parent()
            .ok_or_else(|| invalid("cache manifest has no parent directory"))?;
        fs::create_dir_all(parent)?;
        let staging = parent.join(format!(".{}.part", Uuid::now_v7()));
        let mut output = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&staging)?;
        output.write_all(&encoded)?;
        output.flush()?;
        output.sync_all()?;
        drop(output);

        if destination.exists() {
            fs::remove_file(&destination)?;
        }
        fs::rename(&staging, &destination)?;
        Ok(record)
    }

    pub fn lookup_derived_cache(
        &self,
        scope: &str,
        kind: &str,
        fingerprint_sha256: &str,
    ) -> Result<Option<DerivedCacheHit>> {
        validate_scope(scope)?;
        validate_kind(kind)?;
        validate_digest(fingerprint_sha256)?;
        let scope_sha256 = digest_text(scope);
        let manifest = self.derived_cache_manifest_path(&scope_sha256, kind, fingerprint_sha256)?;
        if !manifest.exists() {
            return Ok(None);
        }

        let size = ensure_regular_file(&manifest, "derived cache manifest")?.len();
        if size > MAX_DERIVED_CACHE_MANIFEST_BYTES {
            return Err(StorageError::BlobTooLarge {
                size,
                limit: MAX_DERIVED_CACHE_MANIFEST_BYTES,
            });
        }
        let record: DerivedCacheRecord = serde_json::from_slice(&fs::read(&manifest)?)?;
        if record.format_version != DERIVED_CACHE_FORMAT_VERSION
            || record.scope_sha256 != scope_sha256
            || record.kind != kind
            || record.fingerprint_sha256 != fingerprint_sha256
        {
            return Err(invalid(
                "cache manifest identity does not match requested scope/kind/fingerprint",
            ));
        }
        validate_digest(&record.blob_sha256)?;
        let descriptor = match self.verify_blob(&record.blob_sha256) {
            Ok(value) => value,
            Err(StorageError::BlobMissing { .. }) => return Ok(None),
            Err(error) => return Err(error),
        };
        if descriptor.size_bytes != record.size_bytes {
            return Err(invalid(
                "cache manifest byte length differs from verified blob length",
            ));
        }
        let blob_path = self.verified_blob_path(&record.blob_sha256)?;
        Ok(Some(DerivedCacheHit {
            record,
            blob_path,
            validated_bytes: descriptor.size_bytes,
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    fn digest(label: &str) -> String {
        digest_text(label)
    }

    #[test]
    fn cache_hit_requires_exact_scope_kind_fingerprint_and_verified_bytes() {
        let temp = tempdir().unwrap();
        let store = Store::open(temp.path().join("studio.sqlite3")).unwrap();
        let source = temp.path().join("preview.bin");
        fs::write(&source, b"derived-preview-v1").unwrap();
        let fingerprint = digest("project-generation-profile-and-renderer");

        let record = store
            .put_derived_cache_file(
                "project:018f:generation:0190",
                "preview-index",
                &fingerprint,
                &source,
                37,
            )
            .unwrap();
        let hit = store
            .lookup_derived_cache(
                "project:018f:generation:0190",
                "preview-index",
                &fingerprint,
            )
            .unwrap()
            .unwrap();

        assert_eq!(hit.record, record);
        assert_eq!(hit.record.work_units, 37);
        assert_eq!(hit.validated_bytes, b"derived-preview-v1".len() as u64);
        assert_eq!(fs::read(hit.blob_path).unwrap(), b"derived-preview-v1");

        assert!(
            store
                .lookup_derived_cache(
                    "project:other:generation:0190",
                    "preview-index",
                    &fingerprint,
                )
                .unwrap()
                .is_none()
        );
        assert!(
            store
                .lookup_derived_cache(
                    "project:018f:generation:0190",
                    "caption-sidecar",
                    &fingerprint,
                )
                .unwrap()
                .is_none()
        );
        assert!(
            store
                .lookup_derived_cache(
                    "project:018f:generation:0190",
                    "preview-index",
                    &digest("changed-font-or-renderer"),
                )
                .unwrap()
                .is_none()
        );
    }

    #[test]
    fn same_fingerprint_cannot_silently_alias_different_output() {
        let temp = tempdir().unwrap();
        let store = Store::open(temp.path().join("studio.sqlite3")).unwrap();
        let first = temp.path().join("first.bin");
        let second = temp.path().join("second.bin");
        fs::write(&first, b"first-output").unwrap();
        fs::write(&second, b"different-output").unwrap();
        let fingerprint = digest("same-input-fingerprint");

        store
            .put_derived_cache_file("project:a", "master", &fingerprint, &first, 1)
            .unwrap();
        let error = store
            .put_derived_cache_file("project:a", "master", &fingerprint, &second, 1)
            .unwrap_err();

        assert!(matches!(error, StorageError::InvalidDerivedCache(_)));
        assert!(error.to_string().contains("different verified bytes"));
    }

    #[test]
    fn malformed_kind_and_fingerprint_fail_closed() {
        let temp = tempdir().unwrap();
        let store = Store::open(temp.path().join("studio.sqlite3")).unwrap();

        assert!(matches!(
            store.lookup_derived_cache("scope", "../master", &digest("ok")),
            Err(StorageError::InvalidDerivedCache(_))
        ));
        assert!(matches!(
            store.lookup_derived_cache("scope", "master", "not-a-digest"),
            Err(StorageError::InvalidBlobDigest)
        ));
    }
}
