import {useState} from 'react';
import {Lock,Plus,Trash2} from 'lucide-react';
import type {NativeClip,NativeCurve,NativeKeyframe,NativeNode,NativeNodeField,NativeProperty,NativeProtection} from './nativeTypes';
const properties:NativeProperty[]=['x','y','width','height','scale_x','scale_y','rotation','opacity','blur','clip_top','clip_right','clip_bottom','clip_left'];
const poseFields=['x','y','width','height','scale_x','scale_y','rotation','opacity','z_index'] as const;
const label=(value:string)=>value.replaceAll('_',' ');
function normalizedKey(frame:number,num:number,den:number,property:NativeProperty,value:number,curve:NativeCurve):NativeKeyframe {
  if(!Number.isInteger(frame)||frame<0||!Number.isInteger(num)||!Number.isInteger(den)||num<0||den<=0||num>=den||den>1e9||!Number.isFinite(value))throw new Error('Use an integer frame and a proper nonnegative rational subframe. No frame rounding is applied.');
  if(!num)return {frame,property,value,curve};
  let a=num,b=den;while(b){const r=a%b;a=b;b=r;}
  return {frame,subframe:{num:num/a,den:den/a},property,value,curve};
}
export default function NativeNodeInspector({node,onChange,onProtect,canProtect,busy}:{node:NativeNode;onChange:(node:NativeNode)=>void;onProtect:(protection:NativeProtection,locked:boolean)=>Promise<void>;canProtect:boolean;busy:boolean}) {
  const [frame,setFrame]=useState(0),[num,setNum]=useState(0),[den,setDen]=useState(1),[property,setProperty]=useState<NativeProperty>('opacity'),[value,setValue]=useState(1);
  const [curve,setCurve]=useState<NativeCurve>({kind:'linear'}),[error,setError]=useState<string|null>(null);
  const locked=(property:NativeProperty)=>node.locked_properties.includes(property);
  const fieldLocked=(field:NativeNodeField)=>node.locked_fields?.includes(field) ?? false;
  const updatePose=(field:typeof poseFields[number],raw:string)=>{const value=Number(raw);if(Number.isFinite(value))onChange({...node,pose:{...node.pose,[field]:value}});};
  const queue=()=>{
    try{const key=normalizedKey(frame,num,den,property,value,curve);const t=(k:NativeKeyframe)=>k.frame+(k.subframe?k.subframe.num/k.subframe.den:0);
      const keys=node.keyframes.filter(k=>k.property!==key.property||t(k)!==t(key));keys.push(key);
      keys.sort((a,b)=>a.property.localeCompare(b.property)||t(a)-t(b));onChange({...node,keyframes:keys});setError(null);
    }catch(reason){setError(reason instanceof Error?reason.message:String(reason));}
  };
  const chooseMask=(kind:NativeClip['kind'])=>{
    const clip:NativeClip=kind==='none'?{kind}:kind==='inset'?{kind,top:0,right:0,bottom:0,left:0,radius:0}:kind==='circle'?{kind,radius:50,center_x:50,center_y:50}:{kind,points:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]};
    onChange({...node,clip});
  };
  return <section className="native-node-inspector" aria-label="Native object controls">
    <header><strong>{node.name}</strong><span>{node.content.kind} · {node.id.slice(0,8)}</span></header>
    <label className="production-field"><span>Object name</span><input value={node.name} disabled={busy||fieldLocked('metadata')} onChange={e=>onChange({...node,name:e.target.value})}/></label>
    <div className="native-transform-fields">{poseFields.map(field=><label className="production-field" key={field}><span>{label(field)} {field!=='z_index'&&locked(field)&&<Lock size={10}/>}</span><input type="number" step={field==='opacity'||field.startsWith('scale')?.01:1} value={node.pose[field]} disabled={busy||(field!=='z_index'&&locked(field))} onChange={e=>updatePose(field,e.target.value)}/></label>)}</div>
    {node.content.kind==='text'&&<section className="native-text-controls"><h3>Rich text</h3>
      <div className="native-transform-fields"><label className="production-field"><span>Font size</span><input type="number" value={node.content.size} min={4} max={1024} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='text')onChange({...node,content:{...node.content,size:Number(e.target.value)}});}}/></label>
      <label className="production-field"><span>Line height</span><input type="number" step={.01} value={node.content.line_height} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='text')onChange({...node,content:{...node.content,line_height:Number(e.target.value)}});}}/></label>
      <label className="production-field"><span>Alignment</span><select value={node.content.align} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='text')onChange({...node,content:{...node.content,align:e.target.value as 'left'|'center'|'right'}});}}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label></div>
      {node.content.runs.map((run,index)=><div className="native-text-run" key={index}><label className="production-field"><span>Run {index+1} · preserved line breaks</span><textarea rows={3} value={run.text} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='text')onChange({...node,content:{...node.content,runs:node.content.runs.map((r,i)=>i===index?{...r,text:e.target.value}:r)}});}}/></label>
        <div className="native-transform-fields"><label className="production-field"><span>Paint</span><input type="color" value={run.color.slice(0,7)} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='text')onChange({...node,content:{...node.content,runs:node.content.runs.map((r,i)=>i===index?{...r,color:e.target.value}:r)}});}}/></label><label className="production-field"><span>Weight</span><input type="number" step={100} min={100} max={900} value={run.weight} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='text')onChange({...node,content:{...node.content,runs:node.content.runs.map((r,i)=>i===index?{...r,weight:Number(e.target.value)}:r)}});}}/></label></div>
      </div>)}<p className="production-help">Exact font bytes and glyph coverage are checked by the native renderer. Missing faces are not substituted.</p>
    </section>}
    {(node.content.kind==='rectangle'||node.content.kind==='ellipse')&&<label className="production-field"><span>Fill</span><input type="color" value={node.content.fill.slice(0,7)} disabled={busy||fieldLocked('content')} onChange={e=>{if(node.content.kind==='rectangle'||node.content.kind==='ellipse')onChange({...node,content:{...node.content,fill:e.target.value}});}}/></label>}
    <div className="native-transform-fields"><label className="production-field"><span>Blend</span><select value={node.blend} disabled={busy||fieldLocked('appearance')} onChange={e=>onChange({...node,blend:e.target.value as NativeNode['blend']})}>{['normal','multiply','screen','overlay','difference','lighten','darken'].map(v=><option key={v} value={v}>{v}</option>)}</select></label><label className="production-field"><span>Blur · pixels</span><input type="number" min={0} max={64} step={.25} value={node.effects.blur} disabled={busy||fieldLocked('appearance')||locked('blur')} onChange={e=>onChange({...node,effects:{...node.effects,blur:Number(e.target.value)}})}/></label></div>
    <label className="production-field"><span>Mask</span><select value={node.clip.kind} disabled={busy||fieldLocked('appearance')} onChange={e=>chooseMask(e.target.value as NativeClip['kind'])}><option value="none">None</option><option value="inset">Inset window</option><option value="circle">Circle</option><option value="polygon">Polygon · numeric source</option></select></label>
    {node.clip.kind==='inset'&&<div className="native-transform-fields">{(['top','right','bottom','left','radius'] as const).map(edge=><label className="production-field" key={edge}><span>{edge}{edge==='radius'?' · px':' · %'}</span><input type="number" min={0} max={edge==='radius'?4096:100} value={node.clip.kind==='inset'?node.clip[edge]:0} disabled={busy||fieldLocked('appearance')} onChange={e=>{if(node.clip.kind==='inset')onChange({...node,clip:{...node.clip,[edge]:Number(e.target.value)}});}}/></label>)}</div>}
    <section className="native-keyframes"><h3>Exact keyframes</h3><p className="production-help">A frame plus a rational subframe preserves authored timing. Output samples remain on the selected frame rate.</p>
      <div className="native-transform-fields"><label className="production-field"><span>Channel</span><select value={property} onChange={e=>setProperty(e.target.value as NativeProperty)}>{properties.map(p=><option key={p} value={p}>{label(p)}</option>)}</select></label><label className="production-field"><span>Value</span><input type="number" step={.01} value={value} onChange={e=>setValue(Number(e.target.value))}/></label><label className="production-field"><span>Frame</span><input type="number" min={0} step={1} value={frame} onChange={e=>setFrame(Number(e.target.value))}/></label><label className="production-field"><span>Subframe numerator</span><input type="number" min={0} value={num} onChange={e=>setNum(Number(e.target.value))}/></label><label className="production-field"><span>Denominator</span><input type="number" min={1} value={den} onChange={e=>setDen(Number(e.target.value))}/></label>
      <label className="production-field"><span>Curve</span><select value={curve.kind} onChange={e=>setCurve(e.target.value==='cubic_bezier'?{kind:'cubic_bezier',x1:.22,y1:0,x2:.36,y2:1}:{kind:e.target.value as 'hold'|'linear'|'ease_out_cubic'|'ease_in_out'})}><option value="hold">Hold</option><option value="linear">Linear</option><option value="ease_out_cubic">Cubic out</option><option value="ease_in_out">Smoothstep</option><option value="cubic_bezier">Custom cubic Bézier</option></select></label></div>
      {curve.kind==='cubic_bezier'&&<div className="native-transform-fields">{(['x1','y1','x2','y2'] as const).map(handle=><label key={handle} className="production-field"><span>{handle}</span><input type="number" min={0} max={1} step={.01} value={curve[handle]} onChange={e=>setCurve({...curve,[handle]:Number(e.target.value)})}/></label>)}</div>}
      <button className="secondary-button" disabled={busy||locked(property)||fieldLocked('keyframes')} onClick={queue}><Plus size={13}/> Stage keyframe</button>
      {error&&<p role="alert" className="production-error">{error}</p>}
      <div className="native-keyframe-list">{node.keyframes.map((key,index)=><div key={`${key.property}-${key.frame}-${key.subframe?.num}-${key.subframe?.den}`}><button className="native-keyframe-select" onClick={()=>{setFrame(key.frame);setNum(key.subframe?.num??0);setDen(key.subframe?.den??1);setProperty(key.property);setValue(key.value);setCurve(key.curve);}}><strong>{label(key.property)}</strong><span>{key.frame}{key.subframe?` + ${key.subframe.num}/${key.subframe.den}`:''} f · {key.value}</span><small>{label(key.curve.kind)}</small></button><button className="icon-button" aria-label={`Remove native keyframe ${index+1}`} disabled={busy||locked(key.property)||fieldLocked('keyframes')} onClick={()=>onChange({...node,keyframes:node.keyframes.filter((_,i)=>i!==index)})}><Trash2 size={12}/></button></div>)}</div>
    </section>
    <details className="native-protection"><summary>Explicit human protections</summary><p className="production-help">Protection changes are separate revisioned operations. Save or discard the current draft before changing a lock.</p>
      {(['content','appearance','parent','keyframes','metadata'] as NativeNodeField[]).map(field=><label className="production-check" key={field}><input type="checkbox" checked={fieldLocked(field)} disabled={!canProtect||busy} onChange={e=>onProtect({kind:'field',field},e.target.checked)}/><Lock size={12}/>{label(field)}</label>)}
      {(['x','y','width','height','rotation','opacity'] as NativeProperty[]).map(p=><label className="production-check" key={p}><input type="checkbox" checked={locked(p)} disabled={!canProtect||busy} onChange={e=>onProtect({kind:'property',property:p},e.target.checked)}/>{label(p)}</label>)}
    </details>
  </section>;
}
