use crate::*;
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
#[serde(rename_all = "kebab-case")]
pub enum RecipeId {
    HeroFocus,
    ContrastPair,
    MeasuredNumber,
    CaptionEmphasis,
    ContextLabel,
    HeroReveal,
    ScreenFocus,
    FlowBridge,
    DeviceStage,
    BrowserStage,
    ResponsiveStory,
    EvidencePair,
    Comparison,
    ReferenceBoard,
    SharedObject,
    FocusTransfer,
    MaskWindow,
    CameraMatch,
    HardCutHold,
    ArcReveal,
    DollyFocus,
    DetailReturn,
    GroupReframe,
    CausalDiagram,
    SeriesReveal,
    StateComparison,
    SystemFlow,
    Repeater,
    InfluenceField,
    PathDistribution,
    GridResponse,
    SeededTexture,
    FocusHit,
    TransitionTail,
    EnergyBed,
    SilenceRelease,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RecipeBackend {
    NativeHtml,
    BlenderStage,
    AudioScore,
}
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum KitId {
    EditorialPrecision,
    KineticStatement,
    ProductStage,
    MaterialStudy,
    CausalLab,
    DocumentarySignal,
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct RecipeDefinition {
    pub id: RecipeId,
    pub canonical_id: String,
    pub version: u32,
    pub family: String,
    pub title: String,
    pub purpose: String,
    pub backend: RecipeBackend,
    pub requires_data: bool,
    pub requires_media: bool,
    pub status: String,
    pub fixture_contract: String,
}
impl RecipeId {
    pub const ALL: [Self; 36] = [
        Self::HeroFocus,
        Self::ContrastPair,
        Self::MeasuredNumber,
        Self::CaptionEmphasis,
        Self::ContextLabel,
        Self::HeroReveal,
        Self::ScreenFocus,
        Self::FlowBridge,
        Self::DeviceStage,
        Self::BrowserStage,
        Self::ResponsiveStory,
        Self::EvidencePair,
        Self::Comparison,
        Self::ReferenceBoard,
        Self::SharedObject,
        Self::FocusTransfer,
        Self::MaskWindow,
        Self::CameraMatch,
        Self::HardCutHold,
        Self::ArcReveal,
        Self::DollyFocus,
        Self::DetailReturn,
        Self::GroupReframe,
        Self::CausalDiagram,
        Self::SeriesReveal,
        Self::StateComparison,
        Self::SystemFlow,
        Self::Repeater,
        Self::InfluenceField,
        Self::PathDistribution,
        Self::GridResponse,
        Self::SeededTexture,
        Self::FocusHit,
        Self::TransitionTail,
        Self::EnergyBed,
        Self::SilenceRelease,
    ];
    pub fn definition(self) -> RecipeDefinition {
        let (family, slug, title, purpose, backend, data, media) = match self {
            Self::HeroFocus => (
                "type",
                "hero-focus",
                "Hero focus",
                "One argument, a readable hold and a deliberate typographic hierarchy",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::ContrastPair => (
                "type",
                "contrast-pair",
                "Contrast pair",
                "Express a semantic contrast without turning every word into an effect",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::MeasuredNumber => (
                "type",
                "measured-number",
                "Measured number",
                "A value with its unit, source, date and uncertainty, not an invented counter",
                RecipeBackend::NativeHtml,
                true,
                false,
            ),
            Self::CaptionEmphasis => (
                "type",
                "caption-emphasis",
                "Caption emphasis",
                "Sequentially stress a small part of a readable statement",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::ContextLabel => (
                "type",
                "context-label",
                "Context label",
                "Place orientation and context without competing with the main evidence",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::HeroReveal => (
                "product",
                "hero-reveal",
                "Product hero reveal",
                "A product argument revealed through typographic and graphic continuity",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::ScreenFocus => (
                "product",
                "screen-focus",
                "Screen focus",
                "Inspect a selected region of a digest-bound source screen",
                RecipeBackend::NativeHtml,
                false,
                true,
            ),
            Self::FlowBridge => (
                "product",
                "flow-bridge",
                "Flow bridge",
                "Explain the relation between two actual source screens",
                RecipeBackend::NativeHtml,
                false,
                true,
            ),
            Self::DeviceStage => (
                "product",
                "device-stage",
                "Device stage",
                "Light and frame original generic device geometry without pretending it is a branded asset",
                RecipeBackend::BlenderStage,
                false,
                false,
            ),
            Self::BrowserStage => (
                "product",
                "browser-stage",
                "Browser stage",
                "Contextualize an imported screenshot in editable generic browser framing",
                RecipeBackend::NativeHtml,
                false,
                true,
            ),
            Self::ResponsiveStory => (
                "layout",
                "responsive-story",
                "Responsive story",
                "Recompose a three-beat argument for landscape, portrait and square",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::EvidencePair => (
                "layout",
                "evidence-pair",
                "Evidence pair",
                "Show comparable source images under an explicit evidence classification",
                RecipeBackend::NativeHtml,
                false,
                true,
            ),
            Self::Comparison => (
                "layout",
                "comparison",
                "Comparison worksheet",
                "Give two claims the same spatial and typographic treatment",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::ReferenceBoard => (
                "layout",
                "reference-board",
                "Reference board",
                "Make contextual observations visible without copying a foreign composition",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::SharedObject => (
                "transition",
                "shared-object",
                "Shared object transition",
                "One persistent object changes context across an editorial boundary",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::FocusTransfer => (
                "transition",
                "focus-transfer",
                "Focus transfer",
                "Move attention between two related objects while preserving both",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::MaskWindow => (
                "transition",
                "mask-window",
                "Mask window",
                "An explicit animated aperture reveals a persistent composition",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::CameraMatch => (
                "transition",
                "camera-match",
                "Camera match",
                "Reframe consistent world coordinates instead of replacing the scene",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::HardCutHold => (
                "transition",
                "hard-cut-hold",
                "Hard cut and hold",
                "A frame-exact discontinuity followed by enough time to read",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::ArcReveal => (
                "camera",
                "arc-reveal",
                "Arc reveal",
                "Reveal a real 3D subject with an editable orbit path and lighting",
                RecipeBackend::BlenderStage,
                false,
                false,
            ),
            Self::DollyFocus => (
                "camera",
                "dolly-focus",
                "Dolly and focus",
                "Coordinate actual perspective travel and a focus-distance change",
                RecipeBackend::BlenderStage,
                false,
                false,
            ),
            Self::DetailReturn => (
                "camera",
                "detail-return",
                "Detail and return",
                "Travel from context to a real geometric detail and back",
                RecipeBackend::BlenderStage,
                false,
                false,
            ),
            Self::GroupReframe => (
                "camera",
                "group-reframe",
                "Group reframe",
                "Keep multiple 3D subjects readable under one camera path",
                RecipeBackend::BlenderStage,
                false,
                false,
            ),
            Self::CausalDiagram => (
                "data",
                "causal-diagram",
                "Causal diagram",
                "Reveal a directed explanation whose edges express dependencies",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::SeriesReveal => (
                "data",
                "series-reveal",
                "Series reveal",
                "Reveal a sourced numerical series with truthful axes and units",
                RecipeBackend::NativeHtml,
                true,
                false,
            ),
            Self::StateComparison => (
                "data",
                "state-comparison",
                "State comparison",
                "Compare observed values on a shared baseline and disclose uncertainty",
                RecipeBackend::NativeHtml,
                true,
                false,
            ),
            Self::SystemFlow => (
                "data",
                "system-flow",
                "System flow",
                "Trace one state through a bounded set of persistent system nodes",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::Repeater => (
                "procedural",
                "repeater",
                "Seeded repeater",
                "Repeat editable shapes under explicit count and spatial rules",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::InfluenceField => (
                "procedural",
                "influence-field",
                "Influence field",
                "Deform a bounded field according to an authored influence function",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::PathDistribution => (
                "procedural",
                "path-distribution",
                "Path distribution",
                "Distribute named editable elements by measured path distance",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::GridResponse => (
                "procedural",
                "grid-response",
                "Grid response",
                "Compose a responsive grid that changes density intentionally",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::SeededTexture => (
                "procedural",
                "seeded-texture",
                "Seeded texture",
                "Produce a controlled original material field with reproducible parameters",
                RecipeBackend::NativeHtml,
                false,
                false,
            ),
            Self::FocusHit => (
                "sound",
                "focus-hit",
                "Focus hit",
                "An original short tonal transient tied to a semantic focus event",
                RecipeBackend::AudioScore,
                false,
                false,
            ),
            Self::TransitionTail => (
                "sound",
                "transition-tail",
                "Transition tail",
                "A bounded generated tail preserves continuity across a cut",
                RecipeBackend::AudioScore,
                false,
                false,
            ),
            Self::EnergyBed => (
                "sound",
                "energy-bed",
                "Energy bed",
                "A quiet original harmonic bed with explicit envelope and level",
                RecipeBackend::AudioScore,
                false,
                false,
            ),
            Self::SilenceRelease => (
                "sound",
                "silence-release",
                "Silence release",
                "An intentional release envelope leads to actual silence",
                RecipeBackend::AudioScore,
                false,
                false,
            ),
        };
        RecipeDefinition {
            id: self,
            canonical_id: format!("motionwright.{family}.{slug}"),
            version: 1,
            family: family.into(),
            title: title.into(),
            purpose: purpose.into(),
            backend,
            requires_data: data,
            requires_media: media,
            status: "candidate_requires_source_bound_native_evidence_and_owner_review".into(),
            fixture_contract:
                "three-aspects_three-locales_seed_stability_native_readback_and_edit_preservation/1"
                    .into(),
        }
    }
}
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
pub struct CreativeKit {
    pub id: KitId,
    pub version: u32,
    pub intent: String,
    pub recipes: Vec<RecipeId>,
    pub constraints: Vec<String>,
}
pub fn creative_kits() -> Vec<CreativeKit> {
    [
        (
            KitId::EditorialPrecision,
            "Information hierarchy before decorative motion",
            vec![
                RecipeId::HeroFocus,
                RecipeId::ContextLabel,
                RecipeId::Comparison,
                RecipeId::HardCutHold,
            ],
            vec![
                "One primary typographic hierarchy per scene",
                "Use quiet holds to make the argument legible",
            ],
        ),
        (
            KitId::KineticStatement,
            "Movement supports a specific rhetorical contrast",
            vec![
                RecipeId::ContrastPair,
                RecipeId::CaptionEmphasis,
                RecipeId::SharedObject,
                RecipeId::FocusTransfer,
            ],
            vec![
                "A motion event must have a narrative reason",
                "Do not animate every word independently",
            ],
        ),
        (
            KitId::ProductStage,
            "Observed interfaces and original generic device geometry",
            vec![
                RecipeId::HeroReveal,
                RecipeId::ScreenFocus,
                RecipeId::BrowserStage,
                RecipeId::DeviceStage,
                RecipeId::ArcReveal,
                RecipeId::DollyFocus,
            ],
            vec![
                "Never invent product behavior as a screenshot",
                "Keep cameras and native source editable",
            ],
        ),
        (
            KitId::MaterialStudy,
            "Light, repetition and spatial relationships reveal form",
            vec![
                RecipeId::SeededTexture,
                RecipeId::Repeater,
                RecipeId::InfluenceField,
                RecipeId::DetailReturn,
            ],
            vec![
                "Procedural density has a fixed budget",
                "Publish the seed and material parameters",
            ],
        ),
        (
            KitId::CausalLab,
            "Explain dependencies and changes of state",
            vec![
                RecipeId::CausalDiagram,
                RecipeId::SystemFlow,
                RecipeId::StateComparison,
                RecipeId::SeriesReveal,
            ],
            vec![
                "Arrows encode a declared relationship",
                "Charts preserve source, baseline and units",
            ],
        ),
        (
            KitId::DocumentarySignal,
            "The source leads; editorial framing remains secondary",
            vec![
                RecipeId::EvidencePair,
                RecipeId::ReferenceBoard,
                RecipeId::ResponsiveStory,
                RecipeId::ContextLabel,
            ],
            vec![
                "Label source classification and licensing",
                "Separate observation from interpretation",
            ],
        ),
    ]
    .into_iter()
    .map(|(id, intent, recipes, rules)| CreativeKit {
        id,
        version: 1,
        intent: intent.into(),
        recipes,
        constraints: rules.into_iter().map(str::to_owned).collect(),
    })
    .collect()
}
